apiVersion: v1
kind: ConfigMap
metadata:
  name: wazuh-agent-config
  namespace: wazuh-agent
data:
  ossec.conf: |
    <ossec_config>
      <client>
        <server>
          <address>192.168.56.109</address>
          <port>1514</port>
          <protocol>tcp</protocol>
        </server>
      </client>

      <localfile>
        <log_format>syslog</log_format>
        <location>/var/log/containers/*.log</location>
      </localfile>

      <localfile>
        <log_format>syslog</log_format>
        <location>/var/log/pods/*/*/*.log</location>
      </localfile>
    </ossec_config>