apiVersion: v1
kind: Pod
metadata:
  name: privileged-debugger
  namespace: de-target
  labels:
    app: privileged-debugger
    lab: detection-engineering
spec:
  containers:
  - name: privileged-debugger
    image: ubuntu:22.04
    command: ["sleep"]
    args: ["36000"]
    securityContext:
      privileged: true
      runAsUser: 0
    volumeMounts:
    - name: host-root
      mountPath: /host
      readOnly: true
  volumes:
  - name: host-root
    hostPath:
      path: /
      type: Directory
  restartPolicy: Never
