apiVersion: v1
kind: Pod
metadata:
  name: red-kubectl
  namespace: pt-red
  labels:
    lab: purple-team
    role: attacker
    purpose: rbac-testing
spec:
  serviceAccountName: red-operator
  restartPolicy: Never
  containers:
  - name: kubectl
    image: bitnami/kubectl:latest
    command:
    - /bin/sh
    - -c
    - sleep 3600
