apiVersion: v1
data:
  password: REDACTED
  username: YWRtaW4=
kind: Secret
metadata:
  creationTimestamp: "2026-07-07T19:49:41Z"
  name: app-secret
  namespace: attack-lab
  resourceVersion: "42911"
  uid: 602cc2f9-7848-4d5b-95d4-521553f1dd57
type: Opaque
