apiVersion: v1
data:
  password: REDACTED
  username: YWRtaW4=
kind: Secret
metadata:
  creationTimestamp: "2026-07-07T19:49:19Z"
  name: app-secret
  namespace: attack-lab
  resourceVersion: "42891"
  uid: ca3404d6-2495-4ef9-b24c-f32307683e87
type: Opaque
