apiVersion: v1
kind: Service
metadata:
  name: exposed-dvwa
  namespace: web-security-lab
spec:
  selector:
    app: dvwa
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32080
  type: NodePort