name: Secure CI/CD Pipeline

on:
  push:
  pull_request:

jobs:
  secure-build:
    name: Test, Scan, and Build Docker Image
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: secure-cicd-docker-pipeline

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Run Gitleaks secret scan
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/repo" \
            zricethezav/gitleaks:latest dir \
            --config="/repo/.gitleaks.toml" \
            --redact \
            --verbose \
            --exit-code 1 \
            /repo

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run basic tests
        run: pytest

      - name: Run pip-audit dependency scan
        run: pip-audit -r requirements.txt

      - name: Build Docker image
        run: docker build -t secure-cicd-flask-app:${{ github.sha }} .
