name: Secure CI/CD Pipeline

on:
  push:
  pull_request:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  secure-build:
    name: Test, Scan, Build, Sign Docker Image
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: secure-cicd-docker-pipeline

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Run Gitleaks secret scan
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/repo" \
            zricethezav/gitleaks:latest dir \
            --config="/repo/.gitleaks.toml" \
            --redact \
            --verbose \
            --exit-code 1 \
            /repo

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run basic tests
        run: pytest

      - name: Run pip-audit dependency scan
        run: pip-audit -r requirements.txt

      - name: Set image name
        run: echo "IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/secure-cicd-flask-app:${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      - name: Run Trivy image scan
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:latest image \
            --scanners vuln \
            --severity CRITICAL \
            --exit-code 1 \
            $IMAGE_NAME

      - name: Log in to GitHub Container Registry
        if: github.event_name == 'push'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Push Docker image to GHCR
        if: github.event_name == 'push'
        run: docker push $IMAGE_NAME

      - name: Install Cosign
        if: github.event_name == 'push'
        uses: sigstore/cosign-installer@v3

      - name: Sign Docker image with Cosign
        if: github.event_name == 'push'
        run: cosign sign --yes $IMAGE_NAME

      - name: Verify Docker image signature
        if: github.event_name == 'push'
        run: |
          cosign verify \
            --certificate-identity-regexp "https://github.com/${{ github.repository }}/.github/workflows/secure-cicd.yml@.*" \
            --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
            $IMAGE_NAME
